







































































































































































































































































































































































































[colors.primary]
background = "#101018"
foreground = "#c5dee4"

[colors.normal]
black = "#101018"
red = "#8D7FB5"
green = "#70A7BD"
yellow = "#6F93CB"
blue = "#7CB4CD"
magenta = "#8C94B9"
cyan = "#84A8C7"
white = "#c5dee4"

[colors.bright]
black = "#899b9f"
red = "#8D7FB5"
green = "#70A7BD"
yellow = "#6F93CB"
blue = "#7CB4CD"
magenta = "#8C94B9"
cyan = "#84A8C7"
white = "#c5dee4"
